#ifndef __LIBMIDI_SPEC_V_1_1_INTERNAL_MIDI_TYPES_HPP__
#define __LIBMIDI_SPEC_V_1_1_INTERNAL_MIDI_TYPES_HPP__

#include "libmidi/spec_v_1_1/channel.hpp"
#include "libmidi/spec_v_1_1/controller_number.hpp"
#include "libmidi/spec_v_1_1/delta_time.hpp"
#include "libmidi/spec_v_1_1/duration.hpp"
#include "libmidi/spec_v_1_1/division.hpp"
#include "libmidi/spec_v_1_1/instrument_family_helper.hpp"
#include "libmidi/spec_v_1_1/enum_instrument_family.hpp"
#include "libmidi/spec_v_1_1/enum_instrument.hpp"
#include "libmidi/spec_v_1_1/key.hpp"
#include "libmidi/spec_v_1_1/key_signature.hpp"
#include "libmidi/spec_v_1_1/enum_message_type.hpp"
#include "libmidi/spec_v_1_1/enum_message_category.hpp"
#include "libmidi/spec_v_1_1/message_type.hpp"
#include "libmidi/spec_v_1_1/midi_controller_data.hpp"
#include "libmidi/spec_v_1_1/midi_format.hpp"
#include "libmidi/spec_v_1_1/enum_percussion.hpp"
#include "libmidi/spec_v_1_1/smpte_offset.hpp"
#include "libmidi/spec_v_1_1/tempo.hpp"
#include "libmidi/spec_v_1_1/tick.hpp"
#include "libmidi/spec_v_1_1/time_signature.hpp"
#include "libmidi/spec_v_1_1/track_count.hpp"
#include "libmidi/spec_v_1_1/chunk_length.hpp"
#include "libmidi/spec_v_1_1/chunk_type.hpp"
#include "libmidi/spec_v_1_1/value.hpp"
#include "libmidi/spec_v_1_1/variable_length_quantity.hpp"
#include "libmidi/spec_v_1_1/variable_message_data.hpp"
#include "libmidi/spec_v_1_1/velocity.hpp"

#include "libmidi/spec_v_1_1/event_base.hpp"
#include "libmidi/spec_v_1_1/event.hpp"
#include "libmidi/spec_v_1_1/head.hpp"
// #include "libmidi/spec_v_1_1/track.hpp"
// #include "libmidi/spec_v_1_1/file.hpp"

#endif	/* __LIBMIDI_SPEC_V_1_1_INTERNAL_MIDI_TYPES_HPP__ */
