#ifndef __LIBMIDI_SPEC_V_1_1_MIDI_CONTROLLER_DATA_HPP__
#define __LIBMIDI_SPEC_V_1_1_MIDI_CONTROLLER_DATA_HPP__

namespace libmidi { namespace spec_v_1_1 {

enum class midi_controller_data_value {
    undefined,
	NA,
	range_0_127,
	on_0_off_127,
	on_gt64_off_lt63,
	zero_only,
	zero_or_number_of_channels,
	};

enum class midi_controller_data_usage {
    undefined,
	MSB,
	LSB,
	Source_Note
	};

// enum class midi_controller_response_needed {
//     equipment_must_respond_in_order_to_comply_with_General_MIDI_level_1,
// 	This_equals_the_number_of_channels,_or_zero_if_the_number_of_channels_equals_the_number_of_voices_in_the_receiver
// };

struct controller_command {
    uint8_t m_id;
    const char* m_name;
    midi_controller_data_value m_data_value;
    midi_controller_data_usage m_data_usage;
};

const controller_command midi_controller_commands[] = 
{
    {0x00, "Bank Select", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x01, "* Modulation wheel", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x02, "Breath control", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x03, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x04, "Foot controller", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x05, "Portamento time", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x06, "Data Entry", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x07, "* Channel Volume (formerly Main Volume)", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x08, "Balance", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x09, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x0A, "* Pan", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x0B, "* Expression Controller", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x0C, "Effect control 1", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x0D, "Effect control 2", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x0E, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x0F, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x10, "General Purpose Controller #1", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x11, "General Purpose Controller #2", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x12, "General Purpose Controller #3", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x13, "General Purpose Controller #4", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x14, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x15, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x16, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x17, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x18, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x19, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x1A, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x1B, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x1C, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x1D, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x1E, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x1F, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x20, "Bank Select", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x21, "Modulation wheel", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x22, "Breath control", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x23, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x24, "Foot controller", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x25, "Portamento time", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x26, "Data entry", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x27, "Channel Volume (formerly Main Volume)", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x28, "Balance", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x29, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x2A, "Pan", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x2B, "Expression Controller", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x2C, "Effect control 1", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x2D, "Effect control 2", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x2E, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x2F, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x30, "General Purpose Controller #1", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x31, "General Purpose Controller #2", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x32, "General Purpose Controller #3", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x33, "General Purpose Controller #4", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x34, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x35, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x36, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x37, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x38, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x39, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x3A, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x3B, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x3C, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x3D, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x3E, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x3F, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x40, "* Damper pedal on/off (Sustain)", midi_controller_data_value::on_gt64_off_lt63, midi_controller_data_usage::undefined},
    {0x41, "Portamento on/off", midi_controller_data_value::on_gt64_off_lt63, midi_controller_data_usage::undefined},
    {0x42, "Sustenuto on/off", midi_controller_data_value::on_gt64_off_lt63, midi_controller_data_usage::undefined},
    {0x43, "Soft pedal on/off", midi_controller_data_value::on_gt64_off_lt63, midi_controller_data_usage::undefined},
    {0x44, "Legato Footswitch", midi_controller_data_value::on_gt64_off_lt63, midi_controller_data_usage::undefined},
    {0x45, "Hold 2", midi_controller_data_value::on_gt64_off_lt63, midi_controller_data_usage::undefined},
    {0x46, "Sound Controller 1 (Sound Variation)", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x47, "Sound Controller 2 (Timbre)", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x48, "Sound Controller 3 (Release Time)", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x49, "Sound Controller 4 (Attack Time)", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x4A, "Sound Controller 5 (Brightness)", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x4B, "Sound Controller 6", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x4C, "Sound Controller 7", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x4D, "Sound Controller 8", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x4E, "Sound Controller 9", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x4F, "Sound Controller 10", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x50, "General Purpose Controller #5", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x51, "General Purpose Controller #6", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x52, "General Purpose Controller #7", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x53, "General Purpose Controller #8", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x54, "Portamento Control", midi_controller_data_value::range_0_127, midi_controller_data_usage::Source_Note},
    {0x55, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x56, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x57, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x58, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x59, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x5A, "Undefined", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x5B, "Effects 1 Depth", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x5C, "Effects 2 Depth", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x5D, "Effects 3 Depth", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x5E, "Effects 4 Depth", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x5F, "Effects 5 Depth", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x60, "Data entry +1", midi_controller_data_value::NA, midi_controller_data_usage::undefined},
    {0x61, "Data entry -1", midi_controller_data_value::NA, midi_controller_data_usage::undefined},
    {0x62, "Non-Registered Parameter Number LSB", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x63, "Non-Registered Parameter Number MSB", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x64, "* Registered Parameter Number LSB", midi_controller_data_value::range_0_127, midi_controller_data_usage::LSB},
    {0x65, "* Registered Parameter Number MSB", midi_controller_data_value::range_0_127, midi_controller_data_usage::MSB},
    {0x66, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x67, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x68, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x69, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x6A, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x6B, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x6C, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x6D, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x6E, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x6F, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x70, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x71, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x72, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x73, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x74, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x75, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x76, "Undefined", midi_controller_data_value::undefined, midi_controller_data_usage::undefined},
    {0x77, "Undefined", midi_controller_data_value::undefined , midi_controller_data_usage::undefined},
    {0x78, "All Sound Off", midi_controller_data_value::zero_only, midi_controller_data_usage::undefined},
    {0x79, "* Reset All Controllers", midi_controller_data_value::zero_only, midi_controller_data_usage::undefined},
    {0x7A, "Local control on/off", midi_controller_data_value::on_0_off_127, midi_controller_data_usage::undefined},
    {0x7B, "* All notes off", midi_controller_data_value::zero_only, midi_controller_data_usage::undefined},
    {0x7C, "Omni mode off (+ all notes off)", midi_controller_data_value::zero_only, midi_controller_data_usage::undefined},
    {0x7D, "Omni mode on (+ all notes off)", midi_controller_data_value::zero_only, midi_controller_data_usage::undefined},
    {0x7E, "Poly mode on/off (+ all notes off)", midi_controller_data_value::zero_or_number_of_channels, midi_controller_data_usage::undefined},
    {0x7F, "Poly mode on (incl mono=off +all notes off)", midi_controller_data_value::zero_only, midi_controller_data_usage::undefined}
};

}}
#endif	/* __LIBMIDI_SPEC_V_1_1_MIDI_CONTROLLER_DATA_HPP__ */
